### PR TITLE
Better thread handling

### PR DESCRIPTION
**Pull request by dhouck**
This will make threads more visible in the ebook output, and usefully link back to where they branch from. It also sets up some machinery which might be used in the future to support branching later on in a thread. The problem with that is it probably requires backwards-incompatible changes to the effulgence protocol buffers, whiich I would rather avoid.

### CODE REVIEW

**Comment by ssafar** [comment]
The table fix sounds good; as for the template reorganization, will we actually need to call the macro on multiple different instances? This being a template, it'd be simpler to just keep everything in order as opposed to bringing the middle to the beginning (and it would also avoid parameter passing).

On the other hand, changing the protobuf format should be okay, especially if it's about adding new fields; it's only us who is using it anyway (and it's supposed to be a "super easy to format by templates" intermediate storage).

**Comment by dhouck** [comment]
I added the macro because, if we are to handle Barbecue Forks and anything else like it, we’ll need to call it recursively. That’s also why I included a `ParentId` parameter.

I was also thinking it’s better to separate it out, like function calls. Even if you only call a function once, it’s sometimes better to make it separate. I didn’t separate it out more because I wasn’t sure you’d agree with that reasoning, even though it’s the same way you coded `gen_epub.py` before switching to `pyratemp`. However, I think some more separation might be necessary if we want the html and epub to be based on mostly the same code, if you still want some minor diferences between the two.

**Comment by dhouck** [comment]
Also, thank you for your comment on adding fields. It got me thinking about better ways to design the new format, and the new idea only adds fields and works far better than my original idea.

My current plan:
Add a `repeated LinearCommentThread successors` and an `optional string ParentID` (if it doesn’t exist, this will be assumed to be the post instead of a comment). The `ParentID` might be redundant, as your comment in the `effulgence.proto` file points out, but it helps a lot with the actual template. Then, I’ll change the template to call that macro recursively (`pyratemp` never seems to explicitly say it supports recursive macros, but it does talk about how recursive macros are good so I assume that works).

**Comment by ssafar** [comment]
I couldn't agree more with the "let's separate out things" line of thinking; it's just their application for templates that I have doubts about. The way I imagine it (which, then, might or might not be the right way to do it), templates contain lots of "how things should look like" and much less "how things work", so that they basically look like the output HTML page so that one could simply use a HTML editor to look at it. For loops just repeat things, so they should be fine, as for recursion, however...

Do we need recursion at all? (I mean, in the template?)

Sure, the input is some tree with nested threads. That said, our output is basically a bunch of comments, one after the other, linearly. So we can keep our fancy tree in the intermediate format and let the template do the hard work of figuring out which one should go first, or it could also be our Python code that flattens the thing out, keeping the "many LinearCommentThreads, each with some comments" structure, so that our template is simpler (it's just for loops). And since we have two output formats (epub with the previous-century HTML for Kindles and the web mirror with the fancy CSS), both with the same ordering and the same links, I think the flattening functionality should rather go into the code, not the template.

Also, we don't actually have to generate nested HTML tags; since threads are so long, the readers wouldn't notice the difference anyway.

So `parent_id` sounds good, but what about a simple comment ID for the successors? Or, even, "list of links before the thread" and "list of links after it"? (Feel free to include everything that is common between the two outputs; we don't have to keep the intermediate format mathematically perfect, after all :))

**Comment by dhouck** [comment]
I think that the flattening really is the job of the view, and that we can make the files look like they’re supposed to.

I believe you’re suggesting that the chapter’s `thread` array would include threads which don’t start at the beginning of the chapter, and each `LinearCommentThread` would include an intro that might be empty (if it’s the only thread) or might be a link back to the parent chapter/comment? I suppose that could work, but the storage format would necessarily get a bit ugly (in the protocol, we’d really have three choices: an int32 comment id, a marker that we should link back to the parent chapter, or neither if there should be no backlink). Moreover, the trees are good for storing and processing; it seems like it really is the responsibility of the view to do the flattening (especially because the current way it’s set up, it wouldn’t actually be flattened; instead, each child thread would be inside the parent thread’s section). I suppose `gen_ebook.py` could pass the template something with a list of threads, where each thread had an intro with HTML pre-rendered by `gen_ebook.py` (and lose the nesting in the HTML file, which as you point out serves little purpose).

I think that if we separated the `THREADS` macro into a different file, we would have two files that would both look like what they were supposed to. Regardless of how we handle the division of labor between the view and the model, I also think we will need to have at least a few different files again, because almost all the templating code should be shared between the two output formats. There are only a few small necessary differences, and it seems like a bad idea to require them to be made in two separate places. For example, even if they need different HTML and CSS for the different outputs’ comment headers, and we need different `<html>` tags for the inclusion of the epub namespaces, we don’t need different threading logic. That should be in a separate file that’s shared by both outputs.

**Comment by dhouck** [comment]
I implemented the rest of the thread branching logic. If you want I’ll find out how to graft the most recent two commits onto a separate branch and do the template without the recursive macro, but I think this gives better results and will allow more code sharing between the output formats.

EDIT: I forgot to add the actual recursion in the template (I thought I’d done that before reading your comment [here](https://github.com/ssafar/effulgence2epub/pull/6#issuecomment-71396375)). I realize that, since we disagree about whether it’s a good thing this might be wasted work, but I wanted to add that anyway so that you could merge this pull request would be complete. In the process of doing so, I ran into trouble, and I don’t know whether that’s because I’m too tired to be coding or because pyratemp doesn’t actually support recursive macro calls (which would make your idea correct by default). I’ll look at it later, but in the mean time I don’t think it would be a good idea to merge this pull request.

EDIT 2: Never mind; I was being stupid. It appears to support recursive macros perfectly, as long as you actually use the recursion variable correctly (see next commit). Again,I am perfectly willing to redo the templating with the code flattening it if you think that’s better, but I really think this is better, especially since it will probably make it easier to share template code between the epub and html outputs)

**Comment by ssafar** [comment]
Actually, it indeed doesn't look as terribly complicated as I imagined :) Okay, let's go with the "recursion in the template" approach then!

Meanwhile, to have something to try it out on, we could also start on parsing the other two TOCs. I'll have a look at them later today!

**Pull request merged**
